package(default_visibility = ["//visibility:public"])

filegroup(
    name = "clang_format_config",
    srcs = [".clang-format"],
)

sh_binary(
    name = "clang_format",
    srcs = ["clang_format.sh"],
)

sh_binary(
    name = "clang_format_check",
    srcs = ["clang_format_check.sh"],
)
